In [2]:
import tensorflow as tf
from tensorflow.keras import models,layers
import matplotlib.pyplot as plt

In [3]:
Image_size = 128
Batch_size = 32

In [4]:
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    "train",
    shuffle =True,
    image_size =(Image_size,Image_size),
    batch_size =Batch_size 
)
    

Found 70295 files belonging to 38 classes.


In [5]:
class_names = dataset.class_names
class_names 

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [6]:
datavalidation = tf.keras.preprocessing.image_dataset_from_directory(
    "valid",
    shuffle =True,
    image_size =(Image_size,Image_size),
    batch_size =Batch_size 
)
    

Found 17572 files belonging to 38 classes.


In [7]:
class_names = datavalidation.class_names
class_names 

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [8]:
for x,y in dataset:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[218.5  207.5  213.5 ]
   [216.75 205.75 211.75]
   [212.25 201.25 207.25]
   ...
   [187.25 175.25 187.25]
   [178.75 166.75 178.75]
   [181.5  169.5  181.5 ]]

  [[202.5  191.5  197.5 ]
   [211.5  200.5  206.5 ]
   [223.5  212.5  218.5 ]
   ...
   [186.75 174.75 186.75]
   [186.75 174.75 186.75]
   [187.25 175.25 187.25]]

  [[209.   198.   204.  ]
   [212.5  201.5  207.5 ]
   [218.5  207.5  213.5 ]
   ...
   [190.   178.   190.  ]
   [184.25 172.25 184.25]
   [183.5  171.5  183.5 ]]

  ...

  [[177.25 164.25 171.25]
   [166.75 153.75 160.75]
   [181.25 168.25 175.25]
   ...
   [181.5  168.5  177.5 ]
   [166.75 153.75 162.75]
   [175.5  162.5  171.5 ]]

  [[175.25 162.25 169.25]
   [172.25 159.25 166.25]
   [178.25 165.25 172.25]
   ...
   [165.25 152.25 161.25]
   [174.   161.   170.  ]
   [178.5  165.5  174.5 ]]

  [[189.   176.   183.  ]
   [182.   169.   176.  ]
   [181.5  168.5  175.5 ]
   ...
   [181.25 168.25 177.25]
   [187.5  174.5  183.5 ]
   [166.75 153.75 16

Building a Model

In [9]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [10]:
model = Sequential()

In [11]:
model.add(Conv2D(filters = 32,kernel_size = 3 ,padding = 'same',activation ='relu',input_shape=[128,128, 3]))
model.add(Conv2D(filters = 32,kernel_size = 3 ,padding = 'same',activation ='relu' ))
model.add(MaxPool2D(pool_size = 2,strides = 2))

C:\Users\lingas\anaconda3\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.add(Conv2D(filters = 64,kernel_size = 3 ,padding = 'same',activation ='relu',input_shape=[128,128, 3]))
model.add(Conv2D(filters = 64,kernel_size = 3 ,padding = 'same',activation ='relu' ))
model.add(MaxPool2D(pool_size = 2,strides = 2))

In [13]:
model.add(Conv2D(filters = 128,kernel_size = 3 ,padding = 'same',activation ='relu'))
model.add(Conv2D(filters = 128,kernel_size = 3 ,padding = 'same',activation ='relu' ))
model.add(MaxPool2D(pool_size = 2,strides = 2))

In [14]:
model.add(Conv2D(filters = 256,kernel_size = 3 ,padding = 'same',activation ='relu'))
model.add(Conv2D(filters = 256,kernel_size = 3 ,padding = 'same',activation ='relu' ))
model.add(MaxPool2D(pool_size = 2,strides = 2))

In [15]:
model.add(Conv2D(filters = 512,kernel_size = 3 ,padding = 'same',activation ='relu'))
model.add(Conv2D(filters = 512,kernel_size = 3 ,padding = 'same',activation ='relu' ))
model.add(MaxPool2D(pool_size = 2,strides = 2))

flatting the dataset

In [16]:

# to avoid overfitting here we are dropping 25% of the 
model.add(tf.keras.layers.Dropout(0.4))

In [17]:
model.add(Flatten())

adding hidden layers

In [18]:
model.add(Dense(units = 1024,activation ='relu'))

In [19]:
model.add(tf.keras.layers.Dropout(0.4)) #To avoid overfitting

In [20]:
##output
model.add(Dense(units = 38,activation ='softmax'))

compiling the model

In [21]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])
 # Use sparse_categorical_crossentropy


In [22]:

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 64, 64, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 64, 64, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 32, 32, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 32, 32, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 32, 32, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 16, 16, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 16, 16, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 16, 16, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 8, 8, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 8, 8, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 8, 8, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 4, 4, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4, 4, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 8192)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1024)                │       8,389,632 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          38,950 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13,140,806 (50.13 MB)

 Trainable params: 13,140,806 (50.13 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
training_history = model.fit(x =dataset,validation_data =datavalidation,epochs = 10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2404s 1s/step - accuracy: 0.4067 - loss: 2.1139 - val_accuracy: 0.8481 - val_loss: 0.4766
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2431s 1s/step - accuracy: 0.8399 - loss: 0.5045 - val_accuracy: 0.9240 - val_loss: 0.2343
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 7309s 3s/step - accuracy: 0.9123 - loss: 0.2749 - val_accuracy: 0.9407 - val_loss: 0.1812
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2192s 998ms/step - accuracy: 0.9400 - loss: 0.1848 - val_accuracy: 0.9486 - val_loss: 0.1519
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2462s 1s/step - accuracy: 0.9542 - loss: 0.1385 - val_accuracy: 0.9619 - val_loss: 0.1143
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 4047s 2s/step - accuracy: 0.9638 - loss: 0.1080 - val_accuracy: 0.9598 - val_loss: 0.1239
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 35305s 16s/step - accuracy: 0.9708 - loss: 0.0869 - val_accuracy: 0.9687 - val_loss: 0.0968
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 3067s 1s/step - accuracy: 0.9

In [24]:
train_loss,train_accuray = model.evaluate(dataset)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 25286s 12s/step - accuracy: 0.9963 - loss: 0.0123


In [30]:
print(train_loss *100,train_accuray * 100)

1.1300413869321346 99.6742308139801


In [31]:
validation_loss,validation_accuray = model.evaluate(datavalidation)

550/550 ━━━━━━━━━━━━━━━━━━━━ 121s 219ms/step - accuracy: 0.9781 - loss: 0.0684


In [27]:
model.save("trained_model.keras")

In [ ]:
training_history.history

In [ ]:
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)
    

In [ ]:
epchos = [i for i in range[1,11]]
plt.plot(epochs,training_history.history['accuracy'],color ='geen',label ="Training_Accuracy")
plt.plot(epochs,training_history.history['val_accuracy'],color ='blue',label ="validation_Accuracy")
plt.xlabel("No .of epchos")
plt.ylabel("accuracy")
plt.legend()
plt.show()

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

In [ ]:

y_pred = model.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

In [ ]:
predicted_categories

In [ ]:

from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
# Precision Recall Fscore
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
plt.figure(figsize=(40, 40))
sns.heatmap(cm,annot=True,annot_kws={"size": 10})

plt.xlabel('Predicted Class',fontsize = 20)
plt.ylabel('Actual Class',fontsize = 20)
plt.title('Plant Disease Prediction Confusion Matrix',fontsize = 25)
plt.show()

In [ ]:
import os
model_version =max([int(i) for i in os.listdir("../models")  + [0] ]) +1
model.save("f../model/{model_version}")